services:
  # PostgreSQL база даних для розробки
  postgres-dev:
    image: postgres:15-alpine
    container_name: github-crm-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: github_crm_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/pgdata
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5433:5432"
    networks:
      - github-crm-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d github_crm_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local

networks:
  github-crm-dev-network:
    driver: bridge 