services:
  postgres:
    image: postgres:15-alpine
    container_name: github-crm-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: github_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - github-crm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d github_crm"]
      interval: 10s
      timeout: 5s
      retries: 5



  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-crm-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/github_crm
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here-change-in-production
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - github-crm-network


volumes:
  postgres_data:
    driver: local

networks:
  github-crm-network:
    driver: bridge 